### ISSUE TITLE
Possible broken test in pandas scientific-hypothesis exercise

### ISSUE THREAD

**Issue by lstmemery** [Zac-HD/escape-from-automanual-testing#10]
Hey there, these exercises have been very helpful to me. However, I think that Pandas exercise in the scientific-hypothesis is not working as intended. Specifically, `contents = f.getvalue()` will always fail.

It works fine in the numpy example because `np.save` detects if the IO object is a stream. The pandas io operations don't make the distinction, so the stream will automatically close. You can't reopen a stream nor can you run the `getvalue` method on a closed object.

This was the workaround I used. It's messy, but it works:

```
def test_dataframe_round_trip(df):
    try:
        with open('temp.pkl', 'wb+') as f:
            df.to_pickle(f, compression=None)
        with open('temp.pkl', 'rb') as f:
            new = pd.read_pickle(f, compression=None)
        # Pandas ships testing helper functions too!
        pd.testing.assert_frame_equal(df, new)
    finally:
        os.remove('temp.pkl')
```

Thanks for the awesome tutorial!

**Comment by Zac-HD** [comment]
Revisiting this for SciPy 2020, it's definitely working for me... maybe you were using an old version of Pandas?
