### ISSUE TITLE
test the untestable feedback

### ISSUE THREAD

**Issue by rsokl** [Zac-HD/escape-from-automanual-testing#4]
### The Water Jug problem
This is **such** a cool problem. It needs a preface and more documentation to make it accessible to students.

### The Towers of Hanoi problem
I love this too. This could also use an explicit introduction to acclimate the students

https://github.com/Zac-HD/escape-from-automanual-testing/blob/f74fe43d3e9b447b9ba00791e3ef75223bec164d/test-the-untestable.py#L88-L89
^ these methods don't seem to exist. Do you mean `self.move("A", "B")`?

### Metamorphic testing and statistics demo: how hard can mean() be anyway?
It took me a while to understand what this problem was getting at. It wasn't clear if the `mean` function was bad, and needed fixing. Am I trying to get the test to fail? Etc.

https://github.com/Zac-HD/escape-from-automanual-testing/blob/f74fe43d3e9b447b9ba00791e3ef75223bec164d/test-the-untestable.py#L189-L196 
^ these instructions need to be moved to the top of the problem

**Comment by Zac-HD** [comment]
Done :smile:
